sudo: required
services: 
  - docker

before_install:
  - docker build -t boris90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true boris90/react-test npm test

after_success:
  - docker build -t boris90/multi-client ./client
  - docker build -t boris90/multi-nginx ./nginx
  - docker build -t boris90/multi-server ./server
  - docker build -t boris90/multi-worker ./worker

  #Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push boris90/multi-client
  - docker push boris90/multi-nginx
  - docker push boris90/multi-server
  - docker push boris90/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-957814146075'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY